### ISSUE TITLE
Add aop_add_afterthrowing

### ISSUE THREAD

**Issue by kdambekalns** [AOP-PHP/AOP#18]
It would be nice to be able to declare advice only after a method throws an exception, using `aop_add_afterthrowing`. The existing `aop_add_after()` would be a "superset" of this, so to speak… See http://flow3.typo3.org/documentation/guide/partiii/aspectorientedprogramming.html#after-throwing-advice for the FLOW3 documentation on that feature.

**Comment by geraldcroes** [comment]
We planned to add a feature named aop_add_exception (maybe the wording could adopt your "afterthrowing") in beta 2.

We will see for the beta 2 if, indeed, aop_add_after should be a superset of aop_add_exception / aop_add_finally (maybe a really good idea)

**Comment by geraldcroes** [comment]
Now that I had some time to think about it, I agree that 

aop_add_after should run whatever the behaviour of the joinpoint is
aop_add_afterreturning should run when the joinpoint returns normally (no exception)
aop_add_afterthrowing should run when an exception is launched.

Thx again for your input, we'll include this in Beta 2

**Comment by kdambekalns** [comment]
Awesome!

**Comment by geraldcroes** [comment]
Done & Tested

e67777e5ed844961a131cd1e06a28f37943e12e6
