### ISSUE TITLE
Access to undefined property results in segmentation fault

### ISSUE THREAD

**Issue by schmittjoh** [AOP-PHP/AOP#27]
When accessing an undefined property I would still expect the default PHP error message, sth like `Undefined property: A\B\C::$d`.

Right now, however, I get a segmentation fault if there are any advices registered.

**Comment by geraldcroes** [comment]
I cannot reproduce your issue. The following passes https://github.com/AOP-PHP/AOP/commit/1fea1d4c0d9f31461aa6cead28c76a9bd40e1af4

can you provide a sample please ?

**Comment by schmittjoh** [comment]
How do you run the test suite?

**Comment by geraldcroes** [comment]
just type `make test`

**Comment by geraldcroes** [comment]
The current version will require libpcre on your computer

**Comment by geraldcroes** [comment]
You can also give me a php sample file that segfault, I will integrate it to the test suites

**Comment by schmittjoh** [comment]
These are the steps to reproduce:

```
git clone git://github.com/schmittjoh/php-debugger.git
curl -s http://getcomposer.org/installer | php
php composer.phar install --dev
phpunit // segfaults
phpunit --filter FileWriter // skips the AOP related tests and passes
```

I can also try to get the extension tests working later today.

**Comment by geraldcroes** [comment]
Thx, I'll transform this into a unit test later today (have to go right now)

**Comment by geraldcroes** [comment]
Julien fixed the issue right now.

**Comment by schmittjoh** [comment]
Thanks.
