### ISSUE TITLE
throw fatal error when give two advices like this.

### ISSUE THREAD

**Issue by reedboat** [AOP-PHP/AOP#29]
``` php
    <?php
    class AdminDeniedException extends Exception {
    }

    function doAdminStuff(){
        echo "do admin stuff\n";
    }
    
    function adviceForDoAdmin(){
        global $role;
        if ( $role != 'admin' ) {
            throw new AdminDeniedException();
        }
    }

    function adviceForException($obj){
        $method = $obj->getFunctionName();
        try {
            $obj->process();
        }
        catch(AdminDeniedException $e){
            echo "no privilige to access $method\n";
        }
    }
    
    aop_add_before('doAdmin*()' , 'adviceForDoAdmin');
    aop_add_around('doAdmin*()', 'adviceForException');    
    
    try {
        doAdminStuff();
    } catch(Exception $e) {
        echo "unknown exception";    
    }
    ?>
```

In code above, I want to use aop to manage priviliges and deal with exceptions. but when i put admin advice before exception advice, it will throw a Fata error as follows.

   "Fatal error: Problem in AOP Callback in /home/kufazhang/workcode/php-dev/c.php on line 26"

But shouldn't it output "unknow exception"?

**Comment by juliens** [comment]
Hi and thx for your bug request.

There definitely is an issue, your code snipet should show "unknown exception !", and obviously not "Problem in AOP callback".

Now, things put aside, the situation here is a bit tricky, as you expected the behaviour to be echoing "no privilege to do ...";

Advices are executed in their registered order. In your case, the "before" advice launch an exception before the around advice could get any chance to catch the exception.
The right order for your wanted behaviour should be 
1) registering the around advice, with the try / catch, so it will be launched "before other advices", getting the opportunity to catch any exceptions
2) registering the other advices.

This is kind of tricky, reason why we will include an aop_add_aftertrhowing method, allowing users to add "catchers", whatever the order of registration is.

So, 
1) you can make your snipet work as you expected by swaping the registration order of your advices
2) we will fix the exception propagation so your current snipet would show "unknown exception"
3) we will include aop_add_afterthrowing to the API very soon to be more user friendly.

Thx again for your report

**Comment by geraldcroes** [comment]
Added your issue as a unit test : https://github.com/AOP-PHP/AOP/commit/96534726f427f8941051ae7410d5dbd26c8bea2b

**Comment by reedboat** [comment]
Yes, it works by swapping the registration order.Look forward to the next version of this great project. thanks.

**Comment by juliens** [comment]
Fixed https://github.com/AOP-PHP/AOP/commit/121728753fc2d658abd23317cb61d5f8f493aff4
