### ISSUE TITLE
Properties?

### ISSUE THREAD

**Issue by beberlei** [AOP-PHP/AOP#3]
First, very useful extension! We can definately use this in Doctrine (optionally) to avoid proxy code generation.

I am not sure if this is in the scope of an AOP extension, but would it be possible to have hooks for property access (read/write) as well? We could use this in Doctrine to implement Change Tracking for objects.

**Comment by geraldcroes** [comment]
Thx for your comment on this extension.

I don't know if including properties is really beyond the scope of AOP but I have to say this was kind of a wanted limitation... until needed.

If we look at the Java world, AspectJ do enables developpers to hook properties (public, protected or private), Spring AOP does not (Java's Proxies only enables developpers to hook methods).

Technically, we looked at it and it is definitely possible. The only remaining question is "performance wise", is it worth it ? Catching properties comes with quite a cost if used (I'll let Julien gives more details on this), but would be transparent for projects that don't take advantage of it. Currently the AOP extension is quite fast and we would like to keep it that way for general purpose, or at least keep it fast while not using the ability to hook properties.

So, as a conclusion, we will include thoose hooks as soon as possible. To do so we'll have to make some tweaks on the selectors syntax, but that is not really a big deal.

Let us know if you have some ideas / comments, we would love to see other people / projects play with this extension.

**Comment by beberlei** [comment]
I guessed there is a performance penalty. Why is it bigger than the one on methods?

In general we have to weigh the performance cost of this vs the benefit we get in not having to do change tracking inside the Doctrine UnitOfWork. This is actually done in PHP right now for Doctrine and its quite expensive task. So It might be the performance hit cancels out, or is even stlil faster.

**Comment by geraldcroes** [comment]
I think this will still be faster than any PHP implementation (and lower in memory usage).

**Comment by geraldcroes** [comment]
Another idea (discussed on PECL) is to add to the pointcut the instance of the object. That would be even faster, and I guess the kind of feature Doctrine would benefit from for tracking changes.

**Comment by juliens** [comment]
Hi guys, here are some clearance on the properties hook.

First, performance wise, adding the property hook won’t cost a microsecond (or maybe one), if users don’t take advantage of it. (Ok, that was quite expected).

Second, if taking advantage of it, it seems that we have to check, for every read / write on a property of every instances of any class if they match the selectors. I don’t think it will be that bad, but properties access happen quite more often than method calls. If we’re adding an instance in the selector syntax, this won’t be an issue at all, for sure.

But enough talking, the best argument is to test it right now, I’ll push a quick test on this very quickly and give you the results
When it’s  done, you’ll be able to do a quick test on your side if you want to.

**Comment by beberlei** [comment]
This is a just me doing premature optimization: Would it be possible to have a syntax that differentiates between read and writes? because property reads are very often, but property writes are not.

Just give me a quick hint if the property branch is raedy, i can probably test this on the weekend.

**Comment by juliens** [comment]
In the catch_property branch you'll get a quick preview of what we can do to hook properties writing operations.

For now I've limited the implementation to the "change notification", you won't be able to do much more.

Of course, consider this as a preview as the API has to be think of thoroughly.

Here is our unit test, should be enougth to understand how to use it.
https://github.com/Juliens/AOP/blob/catch_property/tests/write_properties/001.phpt

Do not hesitate to ask for updates if you need to.

**Comment by beberlei** [comment]
Installed and played with the extension a bit, it works smoothly.

The performance hit for intercepting all properties of an object is about 400%. This is a lot, but i can't easily compare it to the case where I do change tracking manually (yet)

**Comment by beberlei** [comment]
Ok i found a way to test this more easily, see this Gist https://gist.github.com/2975158

Numbrers are:

```
No Tracking: 0.0050
Manual Tracking: 0.1028 (20.6982)
AOP: 0.1882 (37.8753, 1.8299)
```

This is now compared to the explicit change tracking strategy of Doctrine. It looses roughly half the performance compared to explicit code. From my experience this should lead to a little better or equal performance with the the automatic change tracking. Depending on the usage of properties this might be a null-sum game.

**Comment by geraldcroes** [comment]
Thx, 

we'll use your example to work on performances.

**Comment by geraldcroes** [comment]
Looking at your test, little bug founded (I may be wrong), it should be like https://gist.github.com/f4572a9a8c535af8aa16 (you were adding the aop tracking during your first test instead of after)

Perf should be more like (still not good enougth, but better)

```
0.0050
0.0773 (15.3647)
0.0922 (18.3463, 1.1941)
```

**Comment by beberlei** [comment]
Yes, you are right! Thanks for the correction. Results are the same for me. Much better!

**Comment by beberlei** [comment]
numbers get better with "*" instead of two hooks

**Comment by juliens** [comment]
Yes, it can be explained as two hooks have (right now), to make the class/properties matching twice.
As a side note, I think we can benefit from a separate cache for classes and properties

**Comment by juliens** [comment]
I have just pushed a new version with better perf.

**Comment by geraldcroes** [comment]
Results are indeed better

```
0.0030
0.0851 (28.0730)
0.0749 (24.7162, 0.8804)
```

**Comment by beberlei** [comment]
Fantastic! Even faster than writing this manually, i think there is no better outcome :-)

**Comment by juliens** [comment]
Integrated on master (with new syntax). (waiting for doc)

**Comment by beberlei** [comment]
This is fantastic, thank you very much :)
