### ISSUE TITLE
No errors but not working

### ISSUE THREAD

**Issue by canvural** [AOP-PHP/AOP#31]
Hi,

I'm in a weird situation.

AOP installed  successfully. I can see it in `phpinfo()`.

When i'm trying the aop_add_before example on the wiki, i get `do my best stuff !` instead of `I was called before doing stuff...do my best stuff !`

What the problem could be?

**Comment by geraldcroes** [comment]
Hi, 

That is our mistake, the wiki is outdated and does not reflect the Beta 1 API.

for correct use of the extension, you will find this document to be up to date : www.croes.org/gerald/projects/aop/documentation_aop_extension_php.pdf
