### ISSUE TITLE
Wildcard Class and Wildcard Method

### ISSUE THREAD

**Issue by raykolbe** [AOP-PHP/AOP#32]
Hi all,

First off, I'm loving this extension!

I'm not sure if this is currently supported but shouldn't this work:

`My\Namespace\Path\*->*()` or `My\Namespace\Path\*->set*()`

It doesn't appear this is directly referenced in the docs but I assumed it was possible since this works `My\Namespace\Path\MyClass->*()`.

**Comment by juliens** [comment]
Indeed it works as you expected.
Note that you can use two wildcards (**) to span accross multiple namespace. (foo/_/bar will match foo/foo/bar, foo/_*/bar will match foo/foo/bar and foo/anything/…/.. /bar )

Glad to know you enjoy this extension

**Comment by raykolbe** [comment]
@Juliens Are you using v0.1.0 or v0.2.0?

**Comment by juliens** [comment]
`My\Namespace\Path\*->*()` or `My\Namespace\Path\*->set*()`

works in v0.1.0
