### ISSUE TITLE
getTriggeringObject() gives fatal error

### ISSUE THREAD

**Issue by pengux** [AOP-PHP/AOP#35]
The error:
Fatal error: Call to undefined method AopJoinpoint::getTriggeringObject()...

PHP: 5.4.5
AOP 0.2.0

Update: I've discovered that AopJoinpoint has been refactored so the method is now getPointcut().

**Comment by tickleman** [comment]
Is'nt it getObject() ?
"Triggering" term simply disapeared from all AopJoinpoint methods.

**Comment by geraldcroes** [comment]
Right, API had change and we need to finalize the phpdoc. Will be included soon.
