### ISSUE TITLE
aop_add_around() kills the PHP process if the $joinpoint->process() isn't called

### ISSUE THREAD

**Issue by pengux** [AOP-PHP/AOP#37]
When using aop_add_around() and you omitt the call to $joinpoint->-process(), the PHP process ends without any response to the browser. It should maybe raise an exception or warning or return null so the execution can continue.

This issue happened on Windows 7 with PHP 5.4

**Comment by pengux** [comment]
But this is the real AOP-PHP / AOP project :-)

**Comment by tickleman** [comment]
ho, sorry :) I remove my stupid comment ;)

**Comment by juliens** [comment]
Your problem is strange because there is TU on this case .
Can you tell me which DLL do you use ? ( the one in our download section, one that you compile ?)

And can you give us a code example which always fails.

Thx

**Comment by pengux** [comment]
Hi Juliens,

I'm using the DLL that you've sent to me by email some month ago, don't know if you had updated it yet. Here is some code to reproduce the issue:

class Form {

```
public function render(array $aParams = []) {
    return 'foo';
}
```

}

class Csrf {

```
public function aroundFormRender(\AopJoinpoint $joinpoint) {
    # $joinpoint->process();
}
```

}
$oForm = new Form();
$oCsrf = new Csrf();
aop_add_around('Form->render()', array($oCsrf, 'aroundFormRender'));
echo $oForm->render();
echo 'bar';

**Comment by juliens** [comment]
Fixed in the last commit (I try to compile the dll quickly but I must re-install Visual Studio ...)

If you want your code to work, you can just do that in your advice

``` php
public function aroundFormRender(\AopJoinpoint $joinpoint) {
    # $joinpoint->process();
    return null;
}
```
