### ISSUE TITLE
property : How to change assigned value ?

### ISSUE THREAD

**Issue by tickleman** [AOP-PHP/AOP#42]
I see this in your documentation :

``` php
$assigned = $aop_tjp->getAssignedValue();
if ($assigned !== 'PHP') {
$assigned .= ' and PHP';
}
```

$assigned gets a reference to the assigned value, so if we modify it, it alters the assigned value. Cool. (note : it bugs with my current 0.2.0 version of AOP-PHP ! your sample at 2.1.7 of your documentation don't work, $developper->preferences is still "Java". I'd prefer use aop_add_after() but it stills don't work but my turnaround bellow)

But how can I do that stuff : ?

``` php
$assigned = $aop_tjp->getAssignedValue();
$assigned = 'PHP';
```

If I do that assigned value is not changed : in fact $assigned becomes a new string containing "PHP" and is not the reference to the assigned value anymore.

Today's turnaround :

``` php
static $dont_recurse = false;
if (!$done_recurse) {
$assigned = $aop_tjp->getAssignedValue();
$object = $aop_tip->getObject();
$property = $aop_top->getPropertyName();
$dont_recurse = true;
$object->$property = 'PHP';
$dont_recurse = false;
}
```

Another way to do that ?

If not, suggested improvement on AOP-PHP :

``` php
$aop_tip->setAssignedValue('PHP');
```

**Comment by juliens** [comment]
Hi

Actually there is a mistake in the doc. In order to have reference you must use & before "getAssignedValue"
https://github.com/AOP-PHP/AOP/blob/master/tests/docsexample/19.phpt#L12

Moreover, setAssignedValue exists, but is not documented yet 
https://github.com/AOP-PHP/AOP/blob/master/tests/docsexample/21.phpt#L18

**Comment by tickleman** [comment]
magnificent ! Thanks a lot for those informations, I will follow unit tests more accutely then.
