### ISSUE TITLE
Memory Leaks?

### ISSUE THREAD

**Issue by lordnynex** [AOP-PHP/AOP#43]
Just installed aop-beta via pecl. While checking to make sure the module is loaded correctly I see the below errors. I'm unclear on how this error occurs but I figured I'd report it anyhow. 

Potentially noteworthy: PHP was compiled from source with  --enable-debug and --enable-maintainer-zts

 php -i |grep -i aop

aop
[Wed Nov 21 16:13:09 2012]  Script:  '-'
/tmp/pear/temp/AOP/aop.c(140) :  Freeing 0x7F5B74F8BBD8 (8192 bytes), script=-
/software/php-5.4.8/Zend/zend_alloc.c(2529) : Actual location (location was relayed)
[Wed Nov 21 16:13:09 2012]  Script:  '-'
/tmp/pear/temp/AOP/aop.c(145) :  Freeing 0x7F5B74F91CF8 (72 bytes), script=-
=== Total 2 memory leaks detected ===

**Comment by romainneutron** [comment]
Same issue here

**Comment by juliens** [comment]
Already fixed in master, it will be in the next release (0.3.0)

Thx for the issue !
