### ISSUE TITLE
Object-oriented style for aop_add_xxx methods

### ISSUE THREAD

**Issue by lisachenko** [AOP-PHP/AOP#49]
It will be nice to have a class for Aop routines, because object oriented style is smarter, allows inheritance and logical composition.

For example:

``` php
$aspect = new Aspect(); // <-- Class defined in the extension
$aspect->addBefore('MyServices->doStuff()', $advice); // <-- aop_add_before()
```

Example of use:

``` php
class TestAspect extends Aspect 
{

    public function aroundStuff(AopJoinPoint $joinpoint)
    {
        $joinpoint->process();
        $returnValue = $joinpoint->getReturnedValue();
        $returnValue = str_replace('best', 'very best', $returnValue);
        $joinpoint->setReturnedValue($returnValue);
    }

    public function register()
    {
        // aop_add_around('MyServices->doStuff()', array($this, 'aroundStuff'));
        $this->addAround('MyServices->doStuff()', array($this, 'aroundStuff'));
    }
}

$testAspect = new TestAspect();
// Object-oriented style with inheritance and encapsulation:
$testAspect->register();
// Procedural style:
// aop_add_around('MyServices->doStuff()', array($testAspect, 'aroundStuff'));
```

**Comment by lordnynex** [comment]
Bumping this in hopes it gets attention from the devs!

**Comment by geraldcroes** [comment]
Hi.

First of all, we do look at our issues and are giving attention to all of them :-) 

As an object oriented geek, I do like OOP style.... but I'm not really sure we need to add this object oriented style in the extension itself.

We really want to keep it stupid simple.

That's not a "no", but a "I'll really have to change my mind on it for it to be in the extension"

**Comment by lisachenko** [comment]
Thanks for your response! 

I'm happy that there is a chance to change your mind on it :-) 

What about having both procedural/OOP style in extension? As far as I know, describing the classes in the extension is not very difficult. So, some extensions offer procedural and object-oriented style, for example: mysqli, stomp, etc.

**Comment by geraldcroes** [comment]
We may do it with the addition of "aop_add"

class diagramm would be something like 

Aspect(Pointcut $p, Advice $a)

Advice //abstract
AroundAdvice
BeforeAdvice
AfterAdvice
AfterReturningAdvice
AfterThrowingAdvice

base interface Pointcut
DynamicPointcut //execution evaluation time
StaticPointcut //once evaluated, result will be remembered

AopPointCut (will have to find another name) //will be the current and default pointcut syntax

But this is in the future... we really focus on stability for the moment. Once done, we will work hard on the API... Then RC & 1.0. And then new features :-)

**Comment by lisachenko** [comment]
Wow! Class diagram looks amazing! )

But stability is a main task for now, agree on that with you.

BTW, discussion about AOP interfaces and classes can be started at aopalliance/php project. I'll be looking forward to your involvement. )
