### ISSUE TITLE
Support multiple selectors or boolean expressions in pointcut expression

### ISSUE THREAD

**Issue by ricksuggs** [AOP-PHP/AOP#50]
I would like to be able to declare more than one Pointcut expression for an advice.

I have seen the boolean operators && and || used in the comments on the following issue, but have not been able to use them within my own expressions. They are not shown in the documentation, and I have not been able to find an existing unit test for them.

Are they actually supported?

https://github.com/AOP-PHP/AOP/issues/19

Thank you.

**Comment by vadimcomanescu** [comment]
Hi. I also tried using logical operators for defining pointcut expressions but without any luck. Are they supported and if not is there any plan in supporting them? If they are supported is there any reference to any kind of documentation in using them? 
AspectJ for example supports this by default and I expected the same behavior. 
Thanks.

**Comment by geraldcroes** [comment]
Hi, 

logical operators are curently not supported. This is definitely a feature we would like to add, but we do not have any roadmap for now.

**Comment by vadimcomanescu** [comment]
Thank you. I did find a workaround for this at the moment by preg_matching on  the AopJoinpoint->getMethodName() and AopJoinPoint->getClassName() and returning from the advice if I don't need to handle it. Anyways, good work guys. :+1:
