### ISSUE TITLE
Improve Introduction

### ISSUE THREAD

**Issue by hammansamuel** [AOP-PHP/AOP#61]
In the introduction, it is not clear where the AOP code should be saved. Will it be in the class file? Thanks!

**Comment by geraldcroes** [comment]
Hi, 

we did not include any best practice in the use of the extensiow, for now.

Aop stuff is code... and developpers should decide by themselves where it should go in their project.

This answer really depends on the environment (Framework or not, Object Oriented or not, ...).

We hope to see in the future frameworks or bundles that will take benefits from AOP, and gives you the answer your looking for.

**Comment by hammansamuel** [comment]
From a pragmatic point of view, this doesn't make any sense, sorry. I'm simply asking how to integrate your library into my code, and the answer doesn't really help me do that.

**Comment by geraldcroes** [comment]
Well,

I really don't want to sound harsh (sorry if I do) but answering this question is as difficult as answering "where should I eat today ?"

I don't know the time of the day, your preferences, your environnement, your budget, .... I just know nothing. I know there are plenty of restaurants, and that tastes differ from one to another.

If you tell me where I should use file_get_contents in my code, I'll tell you where you should use aop_add_\* in your code.

Here are some possibilities

1) You can have a bootstrap file
2) You can have a "bundle boostrap"
3) You can add aspects during execution, where you see it fits
4) You can develop your own framework 
5) You can hook your autoloader 
6) You can ask you "framework X" community where you could use the extension in the "framework X"

AOP is just a paradigm, as OOP is a paradigm. 

Answering "where should AOP code should be saved" is like "where should OOP code should be saved"

**Comment by hammansamuel** [comment]
Well, you can use file_get_contents() in index.php. If you want to have a function to get the contents, it can be put in there. Sample code was all I was asking, I don't see the need to get so philosophical. AOP is quite different from knowing when to call a function. If I have a class A and class B, and I want to take out cross-cutting concerns, other PHP-AOP libraries say I should make a class C that has a function that fulfills/implements the cross-cutting concern, and make join points in A, B by using annotations. Just a final note, other people have built PHP-AOP libraries and their documentation is quite explicit to help developers integrate the library into the code, but your library seems to require a heavier dose of theoretical understanding of AOP, so probably not suitable for me. But thanks for taking the time to try and explain things.

**Comment by Nicolab** [comment]
Hello,

code example here :

http://www.croes.org/gerald/blog/aop-php-programmation-orientee-aspect/822/

2013/5/23 Hamman Samuel notifications@github.com

**Comment by geraldcroes** [comment]
The magic of the library is that you can do whatever you want to do AOP with it, and don't need to understand lot's of the AOP theory.

The sample in the basic tutorial was to me enougth to bring a vision to the developpers, without the need to give further guidance.

So imagine you have a class A with some cross cutting concerns somewhere in your code

``` php
<?php
//somewhere in a class file
class A {
   public function someFunction () {
      someCrossCuttingConcerns ();//this is not good
      someConcerns();
   }
}
?>
```

With AOP, you can do this in e.g. aop.php : 

``` php
<?php
//aop.php or anywhere else, that's up to you, you're free
aop_add_before('a->someFunction()', function () {
   someCrossCuttingConcerns();
});
```

Now, you can update class A to remove the cross cutting concerns

``` php
<?php
//somwhere in the code
class A {
   public function someFunction () {
      someConcerns();//all good
   }
}
?>
```

And of course, you'll have to include "aop.php" in, for example, your Front Controller / plugin / main file / ...

``` php
<?php
//index.php
require ('aop.php');

// the rest of the code

```

In the AOP extension, you can choose to implement your aspects in the form you like, as long as it is "callable" (http://php.net/manual/en/language.types.callable.php)

So if you want to, you can update aop.php to make it like : 

``` php
<?php
//aop.php or anywhere else, that's up to you, you're free
class AdvicesCollections {
   public function someAdvice () {
      //cross cutting concerns code
   }
}

aop_add_before('a->someFunction()', 'AdvicesCollections::someAdvice');
//or
$advices = AdvicesCollections();
aop_add_before('a->someFunction()', array($advices, 'someAdvice'));
//or
... you get the point
```

Hope I answered better your question ?
