### ISSUE TITLE
AOP roadmap and stable version

### ISSUE THREAD

**Issue by marek-sykora** [AOP-PHP/AOP#68]
Dear Gerald and Julien,

I consider your extension very powerful, easy to use and would like to compose it into a real application to watch methods and their input parameters. 

Unfortunately the last released version 0.2.2b1 is not stable enough and causes HTTP request abortion in special case.
I found out the bug causing the aborting is fixed in the master version.

The application I currently worked on is a large business web application with important customers (BMW for example), so I cannot afford to use any PHP extension in beta version.

Would you be so kind to share the AOP extension roadmap, please? I would appreciate if you would release a stable version of the extension within few months.

Do not hesitate to contact me directly on marek.sykora@intraworlds.com.

I am looking forward to your reply, with best regards,

Marek Sykora, web developer, 
Intraworlds GmbH

**Comment by geraldcroes** [comment]
Hi and thx for your support.

We currently have a difficult time coping with the PHP 5.5 changes. Julien is struggling quite hard to make this work again. We ended up with the dead line of September 30 to make this up and stable as one of my projects will make benefits of the extension in a production environment (PHP 5.5).

We unfortunately cannot guarantee any stable tag before January 2014, but the extension will surely be tagged RC1 by October.
