### ISSUE TITLE
Don't using a class for constants registration

### ISSUE THREAD

**Issue by stealth35** [AOP-PHP/AOP#7]
I think it's too bad to using a class form the constants registration

use `AOP_AROUND` or `AOP\AROUND`

**Comment by juliens** [comment]
I'm not sure because in phpdoc (ex. PDO) you see :
"uses class constants since PHP 5.1. Prior releases use global constants"

**Comment by stealth35** [comment]
yes but the `PDO`class  has methods and properties not `AOP`

**Comment by geraldcroes** [comment]
I have to admint that the current form of constants was kind of my idea (AOP:: and not AOP_) in the sense I prefer OO style, may the class have properties/methods or not.

I understand your point of view as there's no reason why whe should keep this approach as AOP::\* does not exists at all.

Maybe we could add both ? Or just remove the AOP::*..... gonna ask if there's kind of a convention for this...

**Comment by stealth35** [comment]
Or turn the functions into statics methods (make alias (`FE_ALIAS`) if you would keep the function)

``` php
<?php
class Aop
{
    const AROUND = 1;
    const BEFORE = 2;
    const AFTER = 3;

    public static function addAround($pointcut, callable $callback)
    {
    }

    public static function addBefore($pointcut, callable $callback)
    {
    }

    public static function addAfter($pointcut, callable $callback)
    {
    }

    public static function addFinal()
    {
    }

    public static function addException()
    {
    }
}
```

**Comment by geraldcroes** [comment]
Sometimes I lead myself into ways of thinking I'm affraid of...

You're right, in the current state of the extension, unless as you say we want to move all aop_\* into AOP::\* (wich I'm not sure there's a real good point for doing so), we should go for AOP_*

What do you think Julien ?

**Comment by juliens** [comment]
My first choice was also AOP_, event if I changed it. 
I'll change my mind one more time and make the AOP_ wins. 

Thx making us step back to think twice on some important details.

**Comment by geraldcroes** [comment]
Julien renamed AOP::\* into AOP_*.
I added some Unit Test.

thx for helping us improving this extension
